/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Mizikar.Ryan.Chapter6.Java.Project;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
